# Generated by Django 3.1.5 on 2021-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('todo', 'Todo')], default='todo', max_length=10),
        ),
    ]
